apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: external-secrets
  description: Manages external secrets in Kubernetes.
spec:
  type: infrastructure
  lifecycle: production
  owner: maintainers
  system: core
