apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: external-secrets
  annotations:
    argocd/app-name: external-secrets
    backstage.io/kubernetes-namespace: secrets
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=external-secrets
  description: Manages external secrets in Kubernetes.
spec:
  type: infrastructure
  lifecycle: production
  owner: group:default/platform_maintainers
  system: developer_platform
