ldp:
  syncWave: wave-1

external-secrets:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
  installCRDs: true

  crds:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
    createClusterExternalSecret: true
    createClusterSecretStore: true
    createClusterGenerator: true
    createClusterPushSecret: true
    createPushSecret: true
  

  certController:
    enabled: false

  