{{- if .Values.platform.claims.enabled }}
apiVersion: oidc.ldp/v1alpha1
kind: ClientClaim
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec: {}
{{- end }}
