apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-replicator
  description: Replicates secrets and configmaps across namespaces.
spec:
  type: infrastructure
  lifecycle: production
  owner: maintainers
  system: developer_platform
