apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: crossplane
  description: The cloud native control plane framework.
spec:
  type: infrastructure
  lifecycle: production
  owner: maintainers
  system: developer_platform
