ldp:
  syncWave: wave-3

lldap-chart:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
  secret:
    create: false
    useExisting: true
  ingress:
    enabled: false
  hpa:
    enabled: false