ldp:
  syncWave: wave-3

lldap-chart:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
  podAnnotations:
    reloader.stakater.com/auto: "true"
  secret:
    create: false
    useExisting: true
    name: lldap-credentials
  ingress:
    enabled: false
  hpa:
    enabled: false