---
# Pull Gitea admin token from vcs namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-gitea-token
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitea-secrets
    kind: ClusterSecretStore
  target:
    name: backstage-gitea-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: gitea-admin-token
        property: token
