---
# Pull OIDC client secret from Authelia (auth namespace)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-oidc-client-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: authelia-oidc-client-secrets
    kind: ClusterSecretStore
  target:
    name: backstage-oidc-client-secret
  dataFrom:
  - extract:
      key: backstage-oidc-client-secret
