apiVersion: oidc.ldp/v1alpha1
kind: Client
metadata:
  name: backstage
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  replicateTo: {{ .Release.Namespace }}
