---
# Password generator for Backstage session secret
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: backstage-session-secret-generator
spec:
  length: 64
  digits: 10
  symbols: 0
  noUpper: false
  allowRepeat: true
---
# ExternalSecret to generate the session secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-session-secret
spec:
  refreshInterval: "24h"
  target:
    name: backstage-session-secret
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: backstage-session-secret-generator
