---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: backstage-session-secret-generator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  length: 64
  digits: 10
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-session-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h
  refreshPolicy: CreatedOnce
  target:
    name: backstage-session-secret
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: backstage-session-secret-generator
