apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    argocd/app-name: backstage
    backstage.io/kubernetes-namespace: portal
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=backstage
  description: The developer portal.
spec:
  type: website
  lifecycle: production
  owner: group:default/platform_maintainers
  system: developer_platform
  dependsOn:
    - component:default/traefik
    - component:default/cert-manager
    - component:default/trust-manager
