apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd
  annotations:
    argocd/app-name: argocd
    backstage.io/kubernetes-namespace: orchestration
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=argocd
  description: Declarative GitOps CD for Kubernetes.
spec:
  type: website
  lifecycle: production
  owner: group:default/platform_maintainers
  system: developer_platform
  dependsOn:
    - component:default/traefik
    - component:default/cert-manager
