---
# ClusterPassword generator for ArgoCD client secret
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: argocd-oidc-client-secret-generator
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 64
---
# ClusterExternalSecret for ArgoCD client secret
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: argocd-oidc-client-secret
spec:
  externalSecretName: argocd-oidc-client-secret
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - {{ .Release.Namespace }} # auth
          - orchestration
  refreshInterval: 0
  externalSecretSpec:
    target:
      name: argocd-oidc-client-secret
    dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterPassword
          name: argocd-oidc-client-secret-generator
---
# ClusterPassword generator for Backstage client secret
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: backstage-oidc-client-secret-generator
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 64
---
# ClusterExternalSecret for Backstage client secret
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: backstage-oidc-client-secret
spec:
  externalSecretName: backstage-oidc-client-secret
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - {{ .Release.Namespace }} # auth
          - portal
  refreshInterval: 0
  externalSecretSpec:
    target:
      name: backstage-oidc-client-secret
    dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterPassword
          name: backstage-oidc-client-secret-generator
---
# ClusterPassword generator for Gitea client secret
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: gitea-oidc-client-secret-generator
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 64
---
# ClusterExternalSecret for Gitea client secret
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: gitea-oidc-client-secret
spec:
  externalSecretName: gitea-oidc-client-secret
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - {{ .Release.Namespace }} # auth
          - vcs
  refreshInterval: 0
  externalSecretSpec:
    target:
      name: gitea-oidc-client-secret
      template:
        data:
          secret: "{{ .password }}"
    dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterPassword
          name: gitea-oidc-client-secret-generator
