---
# ClusterGenerator generator for ArgoCD client secret
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: argocd-oidc-client-secret-generator
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 72
      digits: 10
      symbols: 5
      symbolCharacters: "-_~."
      noUpper: false
      allowRepeat: true
---
# ClusterExternalSecret for ArgoCD client secret
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: argocd-oidc-client-secret
spec:
  externalSecretName: argocd-oidc-client-secret
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - {{ .Release.Namespace }} # auth
          - orchestration
  externalSecretSpec:
    target:
      name: argocd-oidc-client-secret
    dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: argocd-oidc-client-secret-generator
---
# ClusterGenerator generator for Backstage client secret
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: backstage-oidc-client-secret-generator
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 72
      digits: 10
      symbols: 5
      symbolCharacters: "-_~."
      noUpper: false
      allowRepeat: true
---
# ClusterExternalSecret for Backstage client secret
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: backstage-oidc-client-secret
spec:
  externalSecretName: backstage-oidc-client-secret
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - {{ .Release.Namespace }} # auth
          - portal
  externalSecretSpec:
    target:
      name: backstage-oidc-client-secret
    dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: backstage-oidc-client-secret-generator
---
# ClusterGenerator generator for Gitea client secret
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: gitea-oidc-client-secret-generator
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 72
      digits: 10
      symbols: 5
      symbolCharacters: "-_~."
      noUpper: false
      allowRepeat: true
---
# ClusterExternalSecret for Gitea client secret
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: gitea-oidc-client-secret
spec:
  externalSecretName: gitea-oidc-client-secret
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - {{ .Release.Namespace }} # auth
          - vcs
  externalSecretSpec:
    target:
      name: gitea-oidc-client-secret
      template:
        data:
          key: "gitea"
          password: "{{ `{{ .password }}` }}"
          secret: "{{ `{{ .password }}` }}"
    dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: gitea-oidc-client-secret-generator
