apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-token-generator
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
---
# Namespace-scoped Role - only has permissions within vcs namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-token-generator-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-token-generator-binding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
  - kind: ServiceAccount
    name: gitea-token-generator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gitea-token-generator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-generate-token
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: gitea-token-generator
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              NAMESPACE="{{ .Release.Namespace }}"

              echo "Waiting for Gitea pod to be ready..."
              kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=gitea -n $NAMESPACE --timeout=300s

              POD_NAME=$(kubectl get pod -l app.kubernetes.io/name=gitea -n $NAMESPACE -o jsonpath="{.items[0].metadata.name}")
              echo "Found Gitea pod: $POD_NAME"

              # Delete existing token if it exists (ignore error)
              echo "Cleaning up old token..."
              kubectl exec -n $NAMESPACE $POD_NAME -- /usr/local/bin/gitea admin user delete-access-token --username gitea_admin --token-name backstage-token || true

              # Generate new token
              echo "Generating new token..."
              TOKEN=$(kubectl exec -n $NAMESPACE $POD_NAME -- /usr/local/bin/gitea admin user generate-access-token --username gitea_admin --token-name backstage-token --scopes write:repository,read:organization,write:organization,read:user,write:admin,write:user --raw)

              if [ -z "$TOKEN" ]; then
                echo "Failed to generate token"
                exit 1
              fi

              echo "Token generated successfully."

              # Store secret in vcs namespace with Replicator annotation to sync to portal
              echo "Creating secret in $NAMESPACE namespace with Replicator annotation..."
              cat <<EOF | kubectl apply -f -
              apiVersion: v1
              kind: Secret
              metadata:
                name: gitea-admin-token
                namespace: $NAMESPACE
                annotations:
                  replicator.v1.mittwald.de/replicate-to: "portal"
              type: Opaque
              stringData:
                token: "$TOKEN"
              EOF

              echo "Done! Secret stored in $NAMESPACE namespace. Replicator will sync to portal."

              # Create default organization if it doesn't exist
              echo "Creating default organization..."
              kubectl exec -n $NAMESPACE $POD_NAME -- wget -q -O- \
                --header="Authorization: token $TOKEN" \
                --header="Content-Type: application/json" \
                --post-data='{"username":"local-developer-platform","full_name":"Local Developer Platform","description":"Platform infrastructure and services","visibility":"public"}' \
                http://localhost:3000/api/v1/orgs 2>/dev/null || echo "Organization may already exist"

              echo "Setup complete!"
      restartPolicy: OnFailure
