---
# ClusterExternalSecret to sync Gitea admin token from vcs namespace to portal namespace
# This enables Backstage to access the Gitea API token without cross-namespace RBAC
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: gitea-admin-token-sync
spec:
  # Name of the ExternalSecret that will be created in target namespaces
  externalSecretName: gitea-admin-token
  # Target the portal namespace
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - portal
  # Refresh interval - how often to check for secret updates
  refreshTime: 1h
  # ExternalSecret spec that will be created in target namespaces
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: gitea-secrets
      kind: ClusterSecretStore
    target:
      name: backstage-gitea-token
      creationPolicy: Owner
    data:
      - secretKey: token
        remoteRef:
          key: gitea-admin-token
          property: token
