ldp:
  syncWave: wave-3

traefik:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

  deployment:
    kind: DaemonSet

  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443

  service:
    spec:
      type: NodePort

  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
