apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id | dump }}
  annotations:
    argocd/app-name: ${{ values.component_id }}
    backstage.io/kubernetes-namespace: ${{ values.component_id }}
    backstage.io/kubernetes-label-selector: kagent=${{ values.component_id }}
    backstage.io/techdocs-ref: dir:.
  description: ${{ values.description | dump }}
  tags:
    - agent
  links:
    - url: https://agents-127-0-0-1.nip.io
      title: kagent UI
spec:
  type: service
  owner: ${{ values.owner | dump }}
  lifecycle: experimental
  dependsOn:
    - component:default/kagent
