---
apiVersion: oidc.ldp/v1alpha1
kind: UserClaim
metadata:
  name: authelia
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  userId: svc_authelia
  email: svc_authelia@ldp.com
  groupName: lldap_password_manager
  passwordSymbols: 6
---
apiVersion: oidc.ldp/v1alpha1
kind: UserClaim
metadata:
  name: maintainer
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  userId: platform_maintainer
  email: platform_maintainer@ldp.com
  groupName: platform_maintainers
---
apiVersion: oidc.ldp/v1alpha1
kind: UserClaim
metadata:
  name: user
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  userId: platform_user
  email: platform_user@ldp.com
  groupName: platform_users
