apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kagent-crds
  description: Custom resource definitions for kagent.
spec:
  type: infrastructure
  lifecycle: production
  owner: group:default/platform_maintainers
  system: developer_platform
