apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reloader
  description: Restarts pods on secret and configmap changes.
spec:
  type: infrastructure
  lifecycle: production
  owner: maintainers
  system: developer_platform
