apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loki
  annotations:
    argocd/app-name: loki
    backstage.io/kubernetes-namespace: observability
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=loki
  description: Stores pod logs so they can be searched in Grafana.
spec:
  type: infrastructure
  lifecycle: production
  owner: group:default/platform_maintainers
  system: developer_platform
