apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gitea-actions
  annotations:
    argocd/app-name: gitea-actions
    backstage.io/kubernetes-namespace: vcs
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=gitea-actions
  description: CI runner for Gitea Actions (act_runner with docker-in-docker).
  tags:
    - ci
spec:
  type: service
  lifecycle: production
  owner: group:default/platform_maintainers
  system: developer_platform
  dependsOn:
    - component:default/gitea
    - component:default/trust-manager
