ldp:
  syncWave: wave-4
  serverSideApply: true

cloudnative-pg:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
  crds:
    create: true
  serviceAccount:
    create: true
    name: cloudnative-pg